<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PermissionTable extends Doctrine_Table {
  public static function getAllPermissions() {
    $ps = Doctrine::getTable('Permission')->findAll();
    $permissions = array();
    foreach($ps as $p) {
      if (!in_array($p['category'], $permissions)) {
        $permissions[$p['category']] = array();
      }
      $permissions[$p['category']][$p['name']] = $p['display_name'];
    }
    
    return $permissions;
  }
}