<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectUserRoleTable extends Doctrine_Table {
  public static function getPermissions($project_id, $user_id) {
    $permissions = array();
    $purs = Doctrine_Query::create()->from('ProjectUserRole pur')->where('pur.project_id = ?', $project_id)->andWhere('pur.user_id = ?', $user_id)->execute(array(), Doctrine::HYDRATE_RECORD);
    foreach($purs as $pusr) {
      $ps = explode(',', $pusr['role']['permissions']);
      foreach($ps as $p) {
        $permissions[$p] = 1;
      }
    }
    return $permissions;
  }
}