<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectTable extends Doctrine_Table {
  public static function retrieveByIdentifier($identifier) {
    return Doctrine_Query::create()->from('Project p')->where('p.identifier = ?', $identifier)->fetchOne();
  }
}