<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Role extends BaseRole {

  protected $permissionsArray = null;

  public function hasPermission($permission) {
    if (is_null($this->permissionsArray)) {
      $this->permissionsArray = explode(',', $this['permissions']);
    }

    return in_array($permission, $this->permissionsArray);
  }
}