<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User extends BaseUser {
  protected function _encrypt($salt, $password) {
    return sha1($password.$salt).'$'.$salt;
  }

  public function setPassword($password) {
    $salt = substr(md5(rand(100000, 999999).'kiwi'), 0, 23);
    parent::_set('password', $this->_encrypt($salt, $password));
  }

  public function checkPassword($password) {
    $secret = $this['password'];
    return $secret == $this->_encrypt(substr($secret, 41, 23), $password);
  }

  public function __toString() {
    return $this['display_name'].'';
  }
}