<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User extends BaseUser {
  public function checkPassword($password) {
    return $this->getPassword() == $password;
  }
}