
project_home:
  url:     /project/:project_id
  param:   { module: project, action: home }

#-------------------------------------------------------------------------------
calendar:
  url:     /project/:project_id/calendar
  param:   { module: calendar, action: index }

#-------------------------------------------------------------------------------
component:
  url:          /project/:project_id/component
  param:        { module: component, action: index }

component_new:
  url:          /project/:project_id/component/new
  param:        { module: component, action: new }

component_edit:
  url:          /project/:project_id/component/:id/edit
  param:        { module: component, action: edit }
  requirements: { id: \d+ }

#-------------------------------------------------------------------------------
milestone:
  url:          /project/:project_id/milestone
  param:        { module: milestone, action: index }

milestone_new:
  url:          /project/:project_id/milestone/new
  param:        { module: milestone, action: new }

milestone_edit:
  url:          /project/:project_id/milestone/:id/edit
  param:        { module: milestone, action: edit }
  requirements: { id: \d+ }

#-------------------------------------------------------------------------------
ticket:
  url:          /project/:project_id/ticket
  param:        { module: ticket, action: index }

ticket_show:
  url:          /project/:project_id/ticket/:id
  param:        { module: ticket, action: show }
  requirements: { id: \d+ }

ticket_new:
  url:          /project/:project_id/ticket/new
  param:        { module: ticket, action: new }

ticket_edit:
  url:          /project/:project_id/ticket/:id/edit
  param:        { module: ticket, action: edit }
  requirements: { id: \d+ }

#-------------------------------------------------------------------------------
settings:
  url:          /project/:project_id/settings
  param:        { module: settings, action: index }

settings_members:
  url:          /project/:project_id/settings/members
  param:        { module: settings, action: members }

settings_member_delete:
  url:          /project/:project_id/settings/members/:id/delete
  param:        { module: settings, action: memberDelete }
  requirements: { sf_method: [delete] }

#-------------------------------------------------------------------------------
login:
  url:   /login
  param: { module: account, action: login }

logout:
  url:   /logout
  param: { module: account, action: logout }

profile:
  url:   /profile
  param: { module: account, action: profile }

profile_edit:
  url:   /profile/edit
  param: { module: account, action: profileEdit }

#-------------------------------------------------------------------------------
user:
  class: sfDoctrineRouteCollection
  options:
    model:                User
    module:               adminUser
    prefix_path:          admin/user
    column:               id
    with_wildcard_routes: true

role:
  class: sfDoctrineRouteCollection
  options:
    model:                Role
    module:               adminRole
    prefix_path:          admin/role
    column:               id
    with_wildcard_routes: true

project:
  class: sfDoctrineRouteCollection
  options:
    model:                Project
    module:               adminProject
    prefix_path:          admin/project
    column:               id
    with_wildcard_routes: true

#-------------------------------------------------------------------------------
homepage:
  url:   /
  param: { module: home, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
