
user:
  class: sfDoctrineRouteCollection
  options:
    model:                User
    module:               adminUser
    prefix_path:          admin/user
    column:               id
    with_wildcard_routes: true

project:
  class: sfDoctrineRouteCollection
  options:
    model:                Project
    module:               adminProject
    prefix_path:          admin/project
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

login:
  url:   /login
  param: { module: account, action: login }

logout:
  url:   /logout
  param: { module: account, action: logout }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
