# default rules
homepage:
  url:   /
  param: { module: home, action: index }

login:
  url:   /login
  param: { module: account, action: login }

logout:
  url:   /logout
  param: { module: account, action: logout }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
