
project_home:
  url:     /project/:identifier
  class:   sfDoctrineRoute
  options: { model: Project, type: object }
  param:   { module: project, action: home }

ticket:
  url:     /project/:identifier/ticket
  class:   sfDoctrineRoute
  options: { model: Project, type: object }
  param:   { module: ticket, action: index }
  requirements:
    sf_method: [get]

ticket_new:
  url:     /project/:identifier/ticket/new
  class:   sfDoctrineRoute
  options: { model: Project, type: object }
  param:   { module: ticket, action: new }

ticket_create:
  url:     /project/:identifier/ticket
  class:   sfDoctrineRoute
  options: { model: Project, type: object }
  param:   { module: ticket, action: create }
  requirements:
    sf_method: [post]

profile:
  url:   /profile
  param: { module: account, action: profile }

profile_edit:
  url:   /profile/edit
  param: { module: account, action: profileEdit }

user:
  class: sfDoctrineRouteCollection
  options:
    model:                User
    module:               adminUser
    prefix_path:          admin/user
    column:               id
    with_wildcard_routes: true

project:
  class: sfDoctrineRouteCollection
  options:
    model:                Project
    module:               adminProject
    prefix_path:          admin/project
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

login:
  url:   /login
  param: { module: account, action: login }

logout:
  url:   /logout
  param: { module: account, action: logout }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
