default:
  http_metas:
    content-type: text/html

  metas:
    title:        Kiwi
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [bp/screen.css, symfony.css]

  javascripts:    [jquery.js, jquery-ui.js, jquery.layout.js]

  has_layout:     true
  layout:         layout
