actAs: [Timestampable]

#-------------------------------------------------------------------------------
User:
  tableName:          user
  columns:
    email:            { type: string(255), notnull: true, unique: true }
    password:         { type: string(64), notnull: true }
    display_name:     { type: string(16), notnull: true, unique: true }
    is_active:        { type: boolean, notnull: true, default: true }
    is_admin:         { type: boolean, notnull: true, default: false }
    language:         { type: string(5), notnull: true }
    theme:            { type: string(32), notnull: true }
    last_login_at:    { type: timestamp }
  relations:
    projects:
      class:          Project
      foreignAlias:   Users
      refClass:       ProjectMember
      local:          user_id
      foreign:        project_id

#-------------------------------------------------------------------------------
Role:
  tableName:          role
  columns:
    role_name:        { type: string(32), notnull: true, name: role_name as name }
    is_builtin:       { type: boolean, notnull: true, default: false }
    permissions:      { type: clob(65532) }

#-------------------------------------------------------------------------------
Permission:
  tableName:          permission
  columns:
    permission_name:  { type: string(64), notnull: true, unique: true, name: permission_name as name }
    category:         { type: string(64), notnull: true }
    display_name:     { type: string(32), notnull: true }

#-------------------------------------------------------------------------------
Project:
  tableName:          project
  columns:
    project_name:     { type: string(128), notnull: true, name: project_name as name }
    project_status:
      type:           enum
      values:         [potential, open, closed]
      default:        potential
  actAs:
    Sluggable:
      fields:         [project_name]
      unique:         true
    Timestampable:    ~

#-------------------------------------------------------------------------------
ProjectMember:
  tableName:          project_member
  columns:
    user_id:          { type: integer, primary: true }
    project_id:       { type: integer, primary: true }
    role_id:          { type: integer }
  relations:
    User:
      local:          user_id
      foreign:        id
      foreignAlias:   ProjectMembers
    Project:
      local:          project_id
      foreign:        id
      foreignAlias:   ProjectMembers

#-------------------------------------------------------------------------------
Component:
  tableName:          component
  columns:
    project_id:       { type: integer, notnull: true }
    component_name:   { type: string(64), notnull: true, name: component_name as name }
    description:      { type: string(255) }
  relations:
    project:
      class:          Project
      foreignAlias:   Components
      local:          project_id
      foreign:        id
      type:           one
      foreignType:    many
  actAs:
    NestedSet:
      hasManyRoots:   true
      rootColumnName: root_id

#-------------------------------------------------------------------------------
Milestone:
  tableName:          milestone
  columns:
    project_id:       { type: integer, notnull: true }
    milestone_name:   { type: string(64), notnull: true, name: milestone_name as name }
    due:              { type: date }
    description:      { type: string(255) }
  relations:
    project:
      class:          Project
      foreignAlias:   Milestones
      local:          project_id
      foreign:        id
      type:           one
      foreignType:    many

#-------------------------------------------------------------------------------
Ticket:
  tableName:          ticket
  columns:
    project_id:       { type: integer, notnull: true }
    component_id:     { type: integer, notnull: true }
    milestone_id:     { type: integer }
    author_id:        { type: integer, notnull: true }
    assigned_to_id:   { type: integer }
    subject:          { type: string(255), notnull: true }
    description:      { type: clob(65532) }
  relations:
    project:
      class:          Project
      foreignAlias:   Tickets
      local:          project_id
      foreign:        id
      type:           one
      foreignType:    many
    component:
      class:          Component
      foreignAlias:   Tickets
      local:          component_id
      foreign:        id
      type:           one
      foreignType:    many
    author:
      class:          User
      foreignAlias:   Tickets
      local:          author_id
      foreign:        id
      type:           one
      foreignType:    many

#-------------------------------------------------------------------------------







